language: generic

services:
  - docker

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - sourceline: 'ppa:adrozdoff/cmake'
    packages:
      - clang-6.0
      - llvm-6.0
      - llvm-6.0-dev
      - lld-6.0
      - cmake

install:
  - export LLVM_POSTFIX=-6.0
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - source $HOME/.cargo/env
  - cargo install --all-features --git https://github.com/MegatonHammer/linkle --force --root .

script:
  - sudo make SHARDS="sudo docker run -v $TRAVIS_BUILD_DIR:/app -w /app crystallang/crystal:nightly shards" CRYSTAL="sudo docker run -v $TRAVIS_BUILD_DIR:/app -w /app crystallang/crystal:nightly crystal" NAME=crystal_nx_poc_$TRAVIS_TAG LINKLE=./bin/linkle


after_success:
  - mv main.ll crystal_nx_poc_$TRAVIS_TAG.ll

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "build/crystal_nx_poc_$TRAVIS_TAG.nro"
      - "build/crystal_nx_poc_$TRAVIS_TAG.nso"
      - "build/crystal_nx_poc_$TRAVIS_TAG.elf"
      - "crystal_nx_poc_$TRAVIS_TAG.ll"
    skip-cleanup: true
    draft: true
    tag_name: $TRAVIS_TAG
    on:
      tags: true
condition: $TRAVIS_OS_NAME = linux